### ISSUE TITLE
Run all these great examples in intellij

### ISSUE THREAD

**Issue by eakarsu** [lucidworks/fusion-spark-bootcamp#5]
All examples are working great. with spark-shell. 
But I like to run them in eclipse or IntelliJ and having all dependency problems witj Intellij.
Can you please share build.sbt or pom.xml top compile and run all scala examples that are loading data into solr.
I appreciate your help

**Comment by kiranchitturi** [comment]
Hi @eakarsu, to compile you need all libs from `${FUSION_HOME}/apps/libs` as dependencies in the IDE. That should help

**Comment by eakarsu** [comment]
I copied all those libs into my project and re-run loading scala application. Still this line is throwing the following error:

var writeToSolrOpts = Map("collection" -> "users", "soft_commit_secs" -> "10", "zkhost" -> "192.168.1.188:9918")

/* Part of my  
val dataDir = "d:\\vagrant\\centos\\ml-100k"

  def main(args:Array[String]) {

    val spark = SparkSession.builder.
      master("local")
      .appName("spark session example")
      .getOrCreate()

    spark.udf.register("toInt", (str: String) => str.toInt)

    var userDF = spark.read.format("com.databricks.spark.csv")
      .option("delimiter", "|").option("header", "false").load(s"${dataDir}/u.user")
    userDF.createOrReplaceTempView("user")
    userDF = spark.sql("select _c0 as user_id,toInt(_c1) as age,_c2 as gender,_c3 as occupation,_c4 as zip_code from user")
    var writeToSolrOpts = Map("collection" -> "users", "soft_commit_secs" -> "10", "zkhost" -> "192.168.1.188")



*/
2018-05-14T13:29:42,857 - INFO  [main-SendThread(192.168.1.188:9918):ClientCnxn$SendThread@1032] - Opening socket connection to server 192.168.1.188/192.168.1.188:9918. Will not attempt to authenticate using SASL (unknown error)
2018-05-14T13:29:43,859 - WARN  [main-SendThread(192.168.1.188:9918):ClientCnxn$SendThread@1162] - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_152]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[client-support-4.0.1-shadow.jar:?]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141) [client-support-4.0.1-shadow.jar:?]
2018

**Comment by kiranchitturi** [comment]
This seems like a networking issue. Make sure your remote box ip and port are accessible from your box. There is no port for zkhost in the below line

```
var writeToSolrOpts = Map("collection" -> "users", "soft_commit_secs" -> "10", "zkhost" -> "192.168.1.188")
```
